# -*- coding: utf-8 -*-
"""DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4PwmeeG4Gtr6XUl-iDqPxVjJgKTCE1a
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data=load_breast_cancer()
data

data_raw=pd.DataFrame(data.data,columns=data.feature_names)

data_raw

data_raw['target'] = data.target

print('Unique target values and their counts:')
display(data_raw['target'].value_counts())

print('\nTarget names:')
display(data.target_names)

X=data_raw.drop("target", axis=1)
Y=data_raw['target']
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

"""**Activation Function**"""

def segmoid(x):
  return 1 / (1 + np.exp(-x))

"""**Perceptrone**"""

def perceptron(x, weights, bias):

  Net = np.dot(x, weights) + bias
  y_predicted = segmoid(Net)
  y_predicted = np.where(y_predicted >= 0.5, 1, 0)
  return y_predicted

"""**update the weight**"""

def update_weight(w, alpha, x, true_target, predicted_output):
  m=len(true_target)
  derivative_cost_function=(1/m)*np.dot(x.T, (true_target - predicted_output))
  new_weight=w+alpha*derivative_cost_function
  return new_weight

def update_bias(b, alpha, x, true_target, predicted_output):
  m=len(true_target)
  derivative_cost_function=(1/m)*np.sum(true_target - predicted_output)
  return b +alpha*derivative_cost_function

def accuracy(prediction, Y_test):
  correct = 0
  Y_test_array = Y_test.values
  for i in range(len(Y_test_array)):
    if Y_test_array[i] == prediction[i]:
     correct += 1
  return correct / len(Y_test_array)

lr=0.01
bias=0
weights=np.zeros(X_train.shape[1])

def epoch(z, initial_weights, initial_bias, learning_rate, X, Y):
  current_weights = initial_weights
  current_bias = initial_bias
  for i in range(z):
    predicted_output = perceptron(X, current_weights, current_bias)
    current_weights = update_weight(current_weights, learning_rate, X, Y, predicted_output)
    current_bias = update_bias(current_bias, learning_rate, X, Y, predicted_output)
  return current_weights, current_bias

# Call epoch and update the global weights and bias
weights, bias = epoch(700, weights, bias, lr, X_train, Y_train)

predictions_proba = perceptron(X_test, weights, bias)


test_accuracy = accuracy(predictions_proba, Y_test)
print(f"Accuracy on the test set: {test_accuracy:.4f}")

predictions_proba = perceptron(X_test, weights, bias)
predictions_proba